2021-05-20 09:27:05,299 INFO    MainThread:97059 [wandb_setup.py:_flush():69] setting env: {}
2021-05-20 09:27:05,299 INFO    MainThread:97059 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-20 09:27:05,299 INFO    MainThread:97059 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Classification/Heart-Disease-UCI/wandb/run-20210520_092705-wjqnfrf3/logs/debug.log
2021-05-20 09:27:05,299 INFO    MainThread:97059 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Classification/Heart-Disease-UCI/wandb/run-20210520_092705-wjqnfrf3/logs/debug-internal.log
2021-05-20 09:27:05,299 INFO    MainThread:97059 [wandb_init.py:init():369] calling init triggers
2021-05-20 09:27:05,299 INFO    MainThread:97059 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-20 09:27:05,300 INFO    MainThread:97059 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 2isn2gnf
2021-05-20 09:27:05,300 INFO    MainThread:97059 [wandb_run.py:finish():1208] finishing run ranuga-d/Heart-Disease-UCI/2isn2gnf
2021-05-20 09:27:05,305 INFO    MainThread:97059 [jupyter.py:save_history():349] saving 37 cells to _session_history.ipynb
2021-05-20 09:27:05,312 INFO    MainThread:97059 [wandb_run.py:_config_callback():787] config_cb ('_wandb', 'session_history') code/_session_history.ipynb None
2021-05-20 09:27:05,331 INFO    MainThread:97059 [jupyter.py:save_ipynb():268] looking for notebook: 00-main.ipynb
2021-05-20 09:27:06,086 INFO    MainThread:97059 [wandb_init.py:_jupyter_teardown():267] saved code and history
2021-05-20 09:27:06,086 INFO    MainThread:97059 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-20 09:27:06,086 INFO    MainThread:97059 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-20 09:27:06,086 INFO    MainThread:97059 [wandb_run.py:_restore():1507] restore
2021-05-20 09:27:11,089 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: None
2021-05-20 09:27:11,516 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
  artifact_count: 3
}
pusher_stats {
  uploaded_bytes: 68590
  total_bytes: 68590
}

2021-05-20 09:27:12,388 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
  artifact_count: 3
}
pusher_stats {
  uploaded_bytes: 68590
  total_bytes: 68590
}

2021-05-20 09:27:12,971 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 68590
  total_bytes: 102623
}

2021-05-20 09:27:13,870 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 102215
  total_bytes: 102623
}

2021-05-20 09:27:13,973 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 102215
  total_bytes: 102623
}

2021-05-20 09:27:14,075 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 102256
  total_bytes: 102623
}

2021-05-20 09:27:14,176 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 102623
  total_bytes: 102623
}

2021-05-20 09:27:14,279 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 102623
  total_bytes: 102623
}

2021-05-20 09:27:14,380 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 102623
  total_bytes: 102623
}

2021-05-20 09:27:14,481 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 102623
  total_bytes: 102623
}

2021-05-20 09:27:14,583 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 102623
  total_bytes: 102623
}

2021-05-20 09:27:14,684 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 102623
  total_bytes: 102623
}

2021-05-20 09:27:14,786 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 102623
  total_bytes: 102623
}

2021-05-20 09:27:14,887 INFO    MainThread:97059 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 102623
  total_bytes: 102623
}

2021-05-20 09:27:16,185 INFO    MainThread:97059 [wandb_run.py:_show_files():1879] logging synced files
2021-05-20 09:27:16,188 INFO    MainThread:97059 [wandb_init.py:init():418] starting backend
2021-05-20 09:27:16,188 INFO    MainThread:97059 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-20 09:27:16,190 INFO    MainThread:97059 [backend.py:ensure_launched():132] starting backend process...
2021-05-20 09:27:16,221 INFO    MainThread:97059 [backend.py:ensure_launched():137] started backend process with pid: 100737
2021-05-20 09:27:16,222 INFO    MainThread:97059 [wandb_init.py:init():423] backend started and connected
2021-05-20 09:27:16,232 INFO    MainThread:97059 [wandb_init.py:init():465] updated telemetry
2021-05-20 09:27:16,233 INFO    MainThread:97059 [wandb_init.py:init():484] communicating current version
2021-05-20 09:27:17,422 INFO    MainThread:97059 [wandb_init.py:init():489] got version response 
2021-05-20 09:27:17,422 INFO    MainThread:97059 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-20 09:27:18,153 INFO    MainThread:97059 [wandb_init.py:init():522] starting run threads in backend
2021-05-20 09:27:23,159 INFO    MainThread:97059 [wandb_run.py:_console_start():1565] atexit reg
2021-05-20 09:27:23,159 INFO    MainThread:97059 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-20 09:27:23,160 INFO    MainThread:97059 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-20 09:27:23,160 INFO    MainThread:97059 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-20 09:27:23,160 INFO    MainThread:97059 [wandb_init.py:init():546] run started, returning control to user process
2021-05-20 09:27:37,757 INFO    MainThread:97059 [wandb_setup.py:_flush():69] setting env: {}
2021-05-20 09:27:37,757 INFO    MainThread:97059 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-20 09:27:37,757 INFO    MainThread:97059 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Classification/Heart-Disease-UCI/wandb/run-20210520_092737-91jyqo9r/logs/debug.log
2021-05-20 09:27:37,757 INFO    MainThread:97059 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Classification/Heart-Disease-UCI/wandb/run-20210520_092737-91jyqo9r/logs/debug-internal.log
2021-05-20 09:27:37,758 INFO    MainThread:97059 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd017ef2630>
2021-05-20 09:27:37,758 INFO    MainThread:97059 [wandb_init.py:init():369] calling init triggers
2021-05-20 09:27:37,758 INFO    MainThread:97059 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-20 09:27:37,758 INFO    MainThread:97059 [wandb_init.py:init():391] re-initializing run, found existing run on stack: wjqnfrf3
2021-05-20 09:27:37,759 INFO    MainThread:97059 [wandb_run.py:finish():1208] finishing run ranuga-d/Heart-Disease-UCI/wjqnfrf3
