2021-05-19 22:57:03,293 INFO    MainThread:709772 [wandb_setup.py:_flush():69] setting env: {}
2021-05-19 22:57:03,293 INFO    MainThread:709772 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-19 22:57:03,293 INFO    MainThread:709772 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Classification/Heart-Disease-UCI/wandb/run-20210519_225703-7sndhaf3/logs/debug.log
2021-05-19 22:57:03,293 INFO    MainThread:709772 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Classification/Heart-Disease-UCI/wandb/run-20210519_225703-7sndhaf3/logs/debug-internal.log
2021-05-19 22:57:03,293 INFO    MainThread:709772 [wandb_init.py:init():369] calling init triggers
2021-05-19 22:57:03,294 INFO    MainThread:709772 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-19 22:57:03,294 INFO    MainThread:709772 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 1qoilwwt
2021-05-19 22:57:03,295 INFO    MainThread:709772 [wandb_run.py:finish():1208] finishing run ranuga-d/Heart-Disease-UCI/1qoilwwt
2021-05-19 22:57:03,302 INFO    MainThread:709772 [jupyter.py:save_history():349] saving 48 cells to _session_history.ipynb
2021-05-19 22:57:03,312 INFO    MainThread:709772 [wandb_run.py:_config_callback():787] config_cb ('_wandb', 'session_history') code/_session_history.ipynb None
2021-05-19 22:57:03,338 INFO    MainThread:709772 [jupyter.py:save_ipynb():268] looking for notebook: 00-main.ipynb
2021-05-19 22:57:04,044 INFO    MainThread:709772 [wandb_init.py:_jupyter_teardown():267] saved code and history
2021-05-19 22:57:04,044 INFO    MainThread:709772 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-19 22:57:04,045 INFO    MainThread:709772 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-19 22:57:04,045 INFO    MainThread:709772 [wandb_run.py:_restore():1507] restore
2021-05-19 22:57:09,046 INFO    MainThread:709772 [wandb_run.py:_wait_for_finish():1657] got exit ret: None
2021-05-19 22:57:09,425 INFO    MainThread:709772 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
  artifact_count: 2
}
pusher_stats {
  uploaded_bytes: 25165
  total_bytes: 25165
  deduped_bytes: 9153
}

2021-05-19 22:57:14,528 INFO    MainThread:709772 [wandb_run.py:_wait_for_finish():1657] got exit ret: None
2021-05-19 22:57:19,629 INFO    MainThread:709772 [wandb_run.py:_wait_for_finish():1657] got exit ret: None
2021-05-19 22:57:24,729 INFO    MainThread:709772 [wandb_run.py:_wait_for_finish():1657] got exit ret: None
2021-05-19 22:57:29,830 INFO    MainThread:709772 [wandb_run.py:_wait_for_finish():1657] got exit ret: None
2021-05-19 22:57:31,056 INFO    MainThread:709772 [wandb_init.py:init():418] starting backend
2021-05-19 22:57:31,056 INFO    MainThread:709772 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-19 22:57:31,058 INFO    MainThread:709772 [backend.py:ensure_launched():132] starting backend process...
2021-05-19 22:57:31,097 INFO    MainThread:709772 [backend.py:ensure_launched():137] started backend process with pid: 711602
2021-05-19 22:57:31,098 INFO    MainThread:709772 [wandb_init.py:init():423] backend started and connected
2021-05-19 22:57:31,124 INFO    MainThread:709772 [wandb_init.py:init():465] updated telemetry
2021-05-19 22:57:31,125 INFO    MainThread:709772 [wandb_init.py:init():484] communicating current version
2021-05-19 22:57:32,035 INFO    MainThread:709772 [wandb_init.py:init():489] got version response 
2021-05-19 22:57:32,036 INFO    MainThread:709772 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-19 22:57:33,761 INFO    MainThread:709772 [wandb_init.py:init():522] starting run threads in backend
2021-05-19 22:57:38,766 INFO    MainThread:709772 [wandb_run.py:_console_start():1565] atexit reg
2021-05-19 22:57:38,766 INFO    MainThread:709772 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-19 22:57:38,766 INFO    MainThread:709772 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-19 22:57:38,766 INFO    MainThread:709772 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-19 22:57:38,767 INFO    MainThread:709772 [wandb_init.py:init():546] run started, returning control to user process
2021-05-19 22:58:06,046 INFO    MainThread:709772 [wandb_setup.py:_flush():69] setting env: {}
2021-05-19 22:58:06,046 INFO    MainThread:709772 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-19 22:58:06,046 INFO    MainThread:709772 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Classification/Heart-Disease-UCI/wandb/run-20210519_225806-cqulxkfg/logs/debug.log
2021-05-19 22:58:06,046 INFO    MainThread:709772 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/Classification/Heart-Disease-UCI/wandb/run-20210519_225806-cqulxkfg/logs/debug-internal.log
2021-05-19 22:58:06,047 INFO    MainThread:709772 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f0c2477a828>
2021-05-19 22:58:06,047 INFO    MainThread:709772 [wandb_init.py:init():369] calling init triggers
2021-05-19 22:58:06,047 INFO    MainThread:709772 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-19 22:58:06,047 INFO    MainThread:709772 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 7sndhaf3
2021-05-19 22:58:06,049 INFO    MainThread:709772 [wandb_run.py:finish():1208] finishing run ranuga-d/Heart-Disease-UCI/7sndhaf3
